@startuml
actor "Active User" as AU
participant "User Application" as UApp
participant "Client Handler" as CH
participant "Reservation Manager" as RM
participant "Car Manager" as CM
participant "Payment Handler" as PH
participant "ModelManager" as MM



actor "Car"
activate Car
activate AU
activate UApp
AU -> UApp : parkCarIntention()
UApp -> UApp : retrieveRealPosition()
'-> client side check to be in safe zone'
activate CH
UApp ->> CH : parkRequest(CarID, AU_ID)
activate RM
CH ->> RM :  parkRequest(CarID, AU_ID)
activate CM
RM ->> CM : getCarInfo(CarID,AU_ID)
CM -> Car : retrieveCarPosition (CarID)
CM <-- Car : <<Current Position>>
RM <<- CM : carStatus(Car)
'Server side check of car position'
RM -> RM : verifyBoundaries(Car)
activate MM
RM ->> CM : terminateRental(CarID, AU_ID)
CM ->> MM : updateStatus(CarID,FREE)
RM ->> RM : computeFare()
CH <<- RM : showFare(Payment)
UApp <<- CH :showFare(Payment)
activate PH
RM ->> PH : makePayment(User, amount)
RM <<- PH : paymentSuccessful(User, PaymentSeqID)

deactivate PH
@enduml
