-- Reserve a car
@startuml
actor "Active User" as AU
participant "User Application" as UApp
participant "Map Provider" as MAP
participant "Client Handler" as CH
participant "Reservation Manager" as RM
participant "Model Manager" as MM
activate AU
activate UApp
activate MAP

== Intialize ==
AU -> UApp: reserveIntention()
UApp -> UApp : retrieveVirtualPositionOnMap()
UApp -> UApp : retrieveRadiusOnMap()
UApp ->> MAP : getAreaMap(location, radius)
UApp ->> CH : getNearAvailableCars(location, radius)
activate CH
activate RM
CH ->> RM : getNearAvailableCars(location, radius)
activate MM
RM ->> MM : getNearAvailableCars(location, radius)
RM <<-- MM : <<Available Cars>>
CH <<-- RM : <<Available Cars>>
UApp <<-- CH : <<Available Cars>>
UApp <<-- MAP : << Data: Map>>

== Wait user selection ==
UApp -> UApp : renderAvailableCars()
AU -> UApp : highlightCar(CarID)
UApp -> UApp : showHiglightedDetail()
AU -> UApp : confirmReservation()

== Make Reservation ==
UApp ->> CH : reserveCar(CarID, AU_ID)
CH ->> RM : reserveCar(CarID, AU_ID)
RM ->> MM : makeReservation(CarID, AU_ID)
CH <<-- RM : <<Confirmed Registration, CarID, AU_ID>>
UApp <<-- CH : <<Confirmed Registration Reg##, CarID>>


UApp -> UApp : showResevationConfirmed()

@enduml
