@startuml
actor ActiveUser as AU
participant ClientApplication as CA
participant ClientHandler as CH
participant RegistrationManager as RM
participant DLValidatorInt as DLV
participant CCValidatorInt as CCV
participant ModelManager as MM

activate AU
AU -> CA : accessRegistrationForm()
activate CA
CA ->> CH : getRegistrationForm() : registrationForm
activate CH
CA <<-- CH
CA -> CA : showRegistrationForm()
CA <- AU : fillRegistrationForm()
CA ->> CH : registerUser(User user)
activate RM
CH ->> RM: registerUser(User user)
activate DLV
RM ->> DLV : checkDL(DrivingLicence dl)
activate CCV
RM ->> CCV : checkCC(CCData ccd)
activate MM
RM ->> MM : checkUser(User user)
RM <<- MM : userAccepted(User user)
RM ->> MM : addUser(User user)
CH <<- RM : userCreated(User user)
CA <<- CH : showRegistrationSuccess()
...
== wait for DLV and CC check ==
...
RM <<-- DLV : success
RM <<-- CCV : success
deactivate DLV
deactivate CCV
CH <<- RM : CCConfirmed()
RM ->> MM : CCConfirmed(User user)
CA <<- CH : CCConfirmed()

CH <<- RM : DLVConfirmed()
RM ->> MM : DLVConfirmed(User user)
CA <<- CH : DLVConfirmed()


@enduml
